[package]
name = "computor_v1"
version = "0.1.0"
authors = ["romainkirszbaum <rkirszba@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
